### ISSUE TITLE
Add a dark-mode switch

### ISSUE THREAD

**Issue by postmodern** [ronin-rb/ronin-app#2]
Add a dark-mode switch to change the `--bg-color` to a dark midnight blue color. See the minimal [JavaScript](https://github.com/postmodern/postmodern.github.io/blob/dc9bd034509745cbba82b5d88d39ee2ae0ee82ca/javascripts/default.js#L1-L35) on [my blog](https://postmodern.github.io) as an example.

**Comment by SarthakSanjay** [comment]
Hey postmodern , seen your frontend and its great , I would like to contribute , can you assign me

**Comment by postmodern** [comment]
@SarthakSanjay Sure. Please see the [CONTRIBUTING](https://github.com/ronin-rb/ronin-app/blob/main/CONTRIBUTING.md) file. I want to avoid using any JavaScript frameworks, plugins, npm modules, etc, and just want to keep everything minimal vanilla ES6+ JavaScript and CSS4.

**Comment by postmodern** [comment]
@SarthakSanjay since I haven't heard back from you, I decided to implement a basic dark-mode button. Feel free to recommend any improvements to it:
https://github.com/ronin-rb/ronin-app/compare/main...top-menu-and-dark-mode
