### ISSUE TITLE
Add pagination to `/db/*` views

### ISSUE THREAD

**Issue by postmodern** [ronin-rb/ronin-app#21]
As the number of `IPAddress`es, `HostName`s, and `URL`s increase in the database, there should be pagination on the `views/db/*.erb` views which list the records.

## Available Options

* [sinatra-paginate](https://github.com/deepfryed/sinatra-paginate)
* [pagy](https://medium.com/@vfreefly/how-to-use-pagy-with-sequel-and-sinatra-157dfec1c417)
* [kaminari-sinatra](https://github.com/kaminari/kaminari-sinatra)

**Comment by postmodern** [comment]
[`kaminari-sinatra` and `kaminari-activerecord`](https://github.com/kaminari/kaminari#other-frameworklibrary-support) looks like the most promising.

**Comment by AI-Mozi** [comment]
I used `pagy` only. What convinced you to `kaminari`?

**Comment by postmodern** [comment]
`kaminari` supports Sinatra and ActiveRecord. I'm willing to try `pagy`.

**Comment by postmodern** [comment]
Implemented by PR #65.
