### ISSUE TITLE
Add a `GET /vulns` route

### ISSUE THREAD

**Issue by postmodern** [ronin-rb/ronin-app#34]
Add a `GET /vulns` route and form for scanning a URL for web vulnerabilities using [ronin-vulns](https://github.com/ronin-rb/ronin-vulns#readme).

**Comment by AI-Mozi** [comment]
`lfi`, `rfi`, `sqli` etc. should be added to into advanced options and displayed as for example `lfi`: <place_for_key> <place_for_value> ?

**Comment by postmodern** [comment]
@AI-Mozi correct. All of the vuln-specific options would be grouped into sections under an `Advanced Options` `div`. There would also be a `HTTP` section for things like `headers`, `cookie`, `user_agent`, etc. The only required option would be a URL.

**Comment by postmodern** [comment]
Implemented by PR #64.
