### ISSUE TITLE
Improve the layout of the `/nmap` Advanced Options

### ISSUE THREAD

**Issue by postmodern** [ronin-rb/ronin-app#49]
The Advanced Options section on the `/nmap` form is very long and needs better grouping/organization.
![localhost_1337_nmap](https://github.com/ronin-rb/ronin-app/assets/12671/b1771462-a40c-408d-9a87-1f286b60109d)

**Comment by Hardikbalwani** [comment]
can i work on this issue?

**Comment by postmodern** [comment]
@Hardikbalwani yes you can.

Note, if you're planning on participating in [Hacktoberfest](https://hacktoberfest.com/), it officially starts in three weeks. If you submit a PR before October 1st, I'm not sure if it will count for Hacktoberfest?

**Comment by postmodern** [comment]
For inspiration, the official Zenmap GUI groups options into tabs:

![nmap GUI screenshot](https://nmap.org/zenmap/images/zenmap-profeditor-534x527.png)

**Comment by postmodern** [comment]
@sivangbagri feel free to start working on this. I do not assign issues to new contributors, because every time I have done that in the past, the new contributor would disappear and the issue would remain open.

**Comment by postmodern** [comment]
Implemented by PR #104.
