### ISSUE TITLE
Make Ronin banner smaller

### ISSUE THREAD

**Issue by AI-Mozi** [ronin-rb/ronin-app#55]
The banner is too tall on smaller monitors (< 4K) which causes the user to always have to scroll down.

**Comment by AI-Mozi** [comment]
Also navbar disappears at width < 1025px.

**Comment by postmodern** [comment]
I reduced the logo size to 75%.
![localhost_1337_](https://github.com/ronin-rb/ronin-app/assets/12671/9419818b-3ebb-4d66-84f2-d261fa0db130)
