### ISSUE TITLE
Use `Sinatra::Router` to split up `App` into multiple classes?

### ISSUE THREAD

**Issue by postmodern** [ronin-rb/ronin-app#77]
The `app.rb` file is getting quite large. Perhaps we could use [Sinatra::Router](https://github.com/brandur/sinatra-router#readme) to split up the `App` class into multiple sub-App classes that are routed together?

**Comment by AI-Mozi** [comment]
Currently moving `/db/*` routes outside of a `app.rb` would be enough.
I though about moving `scanning` section (`nmap`, `masscan`, `recon`, `vulns`, `spider`) also, but it not as huge as `db`.

I was wondering if we should create `db_routes.rb` file in root directory or maybe `api/db.rb` or `routes/db.rb`? (I think creating additional namespace requires changes in views directory structure)

Beside moving `db`, we could consider making it more compact. Most of these routes are repeatable so we could define them similar to what we did for `notes`.

**Comment by AI-Mozi** [comment]
Hmm.. maybe instead of creating new class for `db` we should just "compact" them as I mentioned before?

**Comment by AI-Mozi** [comment]
But on the other side It might be much less readable..

**Comment by postmodern** [comment]
Another downside would be that if we split apart the app into multiple apps, the `/db/` app would still be giant, as that is where the majority of the routes are.

**Comment by postmodern** [comment]
A simpler alternative to using `Sinatra::Router`, would be to just open up the class again in multiple files.

`app.rb`:
```ruby
class App < Sinatra::Base
  ...
end

require './app/db'
require './app/scanning'
```

`app/db.rb`:
```ruby
class App < Sinatra::Base
  get '/db/...' do
    ...
  end
end
```

**Comment by postmodern** [comment]
Yeah let's split the `app.rb` file apart by just re-opening the `App` class. I will make a new issue.
