### ISSUE TITLE
`urls` for `UrlQueryParamName`?

### ISSUE THREAD

**Issue by AI-Mozi** [ronin-rb/ronin-app#80]
`<% @url_query_param_name.urls.each do |url| %>` is present in show view for `URLQueryParamNames`, but `urls` is not defined in[ `URLQueryParamName`](https://github.com/ronin-rb/ronin-db-activerecord/blob/0.2.0/lib/ronin/db/url_query_param_name.rb) model.

**Comment by postmodern** [comment]
There's a `URLQueryParam#urls` association now in the `0.2.0` branch.
https://github.com/ronin-rb/ronin-db-activerecord/commit/0a692a7f47efc0db648cdc32fd365b83281054fe
