### ISSUE TITLE
`Notes` view for `PhoneNumber` raises an error.

### ISSUE THREAD

**Issue by AI-Mozi** [ronin-rb/ronin-app#81]
Show view for `PhoneNumber` model raises an `SQLite3::SQLException: no such column: ronin_notes.phone_number_id`.

**Comment by AI-Mozi** [comment]
Hmm.. it might be a problem for my local development env.

**Comment by postmodern** [comment]
@AI-Mozi create re-migrating your database. The column should be added in migration [`0044_create_ronin_notes_table.rb`](https://github.com/ronin-rb/ronin-db-activerecord/blob/0a692a7f47efc0db648cdc32fd365b83281054fe/db/migrate/0044_create_ronin_notes_table.rb#L103-L106).

**Comment by postmodern** [comment]
This appears to be fixed now.
